### ISSUE TITLE
Can't use with czmq-ffi-gen 0.9.x

### ISSUE THREAD

**Issue by kou** [paddor/cztop#10]
We can't use CZTop with czmq-ffi-gen 0.9x because of `spec.add_runtime_dependency "czmq-ffi-gen", "~> 0.8.3"`: https://github.com/paddor/cztop/blob/master/cztop.gemspec#L21

Could you update the version?

**Comment by paddor** [comment]
Thanks. Working on it...

**Comment by paddor** [comment]
All of a sudden, for some of CZMQ's functions (the ones that return a char pointer), I don't get an FFI::Pointer back, but a String itself, so it crashes when CZTop tries to call `#read_string` on it. I wonder why... it has to do with the new version of czmq-ffi-gen. Do you know anything about this? I don't see anything related in the Ruby binding within the CZMQ project itself.

**Comment by paddor** [comment]
The reason seems to be zeromq/czmq@8b31e2e38f0, which changed some return types from mutable string to constant string, which made zproject's ruby code generator decide to return a `String` instead of an `FFI::Pointer`. In the meantime, using an unaffected older version of the generated binding (czmq-ffi-gen), CZTop continued to work anyway, since it just read the string pointed to by the pointer using `FFI::Pointer#read_string`.

I'll just fix the affected lines by removing the call to `#read_string` and release a new version of CZTop.

**Comment by paddor** [comment]
Okay, I've released CZTop 0.6.0. :-)

**Comment by kou** [comment]
Thanks!
