### ISSUE TITLE
Issue dealing with Push Pull Socket

### ISSUE THREAD

**Issue by gaurav-teliax** [paddor/cztop#15]
I ran into couple issues when using PUSH/PULL socket. 

**ISSUE 1**: 
```
cztop-0.11.4/lib/cztop/has_ffi_delegate.rb:26:in `attach_ffi_delegate': No such device (Errno::ENODEV)
``` 
Over TCP socket. I see the get above error.

Here how my Sender and Receive look.
```
## receiver.rb
require 'cztop'
@sock = CZTop::Socket::PULL.new("tcp://localhost:4545")
loop { msg = @sock.receive ; puts #{Process.pid} ---- #{msg.to_a}"; sleep 2} 
```
```
## sender.rb
require 'cztop'

# bind
socket = CZTop::Socket::PUSH.new("tcp://*:4545")
i = 0
loop {  socket << ["simple", "message", sprintf("%d", i)] ; i +=1 }
```
**ISSUE 2:**
 When using `IPC`:  As per I understand,  with PUSH socket one can attach multiple PULL sockets  and zeroMQ do a fair scheduling and distribute messages to each PULL socket worker.

But I when I ran the above code over `IPC` . I see only the **one worker** (all the time) receiving all the messages sent by server. (Not sure why is that so, may be I have missed some `socket option` I believe )

```
## sender.rb
socket = CZTop::Socket::PUSH.new("ipc:///tmp/push-pull.sock")
i = 0
loop {  socket << ["simple", "message", sprintf("%d", i)] ; i +=1 }
```

```
## receiver.rb
require 'cztop'
@sock = CZTop::Socket::PULL.new("ipc:///tmp/push-pull.sock")
loop { msg = @sock.receive ; puts #{Process.pid} ---- #{msg.to_a}"; sleep 2} 
```

Just so, I have tested the above with `ffi-rzmq` seem to work as expected. (both over TCP and IPC socket)
```
##sender
require 'ffi-rzmq'

context = ZMQ::Context.new(1)
puts "--"
# Socket to send messages on
sender = context.socket(ZMQ::PUSH)
sender.bind("tcp://*:4545")
t = 0  
loop do 
  sender.send_string(t.to_s)
  t += 1
  sleep 2
end
```

```
## receiver.rb
require 'ffi-rzmq'

context = ZMQ::Context.new(1)

receiver = context.socket(ZMQ::PULL)
receiver.connect("tcp://localhost:4545")


while true
  receiver.recv_string(msec = '')
  puts "--- #{msec}"
end
```

Definitely missing something not sure what? Any Clue ?

**Comment by paddor** [comment]
As for the first issue, I think the problem is that PULL sockets bind by default, and PUSH sockets connect by default (see [zsock(3)](http://czmq.zeromq.org/czmq4-0:zsock) of CZMQ), which probably means you cannot pass `tcp://*:4545`. The other way around (binding to `tcp://*:4545` and connecting to `tcp://localhost:4545`) should work. The `ffi-rzmq`-based example works because you explicitly bind the PUSH socket and connect the PULL socket (see [CZTop::Socket#bind](http://www.rubydoc.info/github/paddor/cztop/CZTop%2FSocket:bind) and [CZTop::Socket#connect](http://www.rubydoc.info/github/paddor/cztop/CZTop%2FSocket:connect)).

That's probably also the reason for the second issue. You can connect to an endpoint many times, but bind to an endpoint only once.

**Comment by gaurav-teliax** [comment]
Fair enough Thanks for the reply. Sorry It took me long to reply back.
