### ISSUE TITLE
Reported performance difference in throughput tests

### ISSUE THREAD

**Issue by prdn** [paddor/cztop#16]
Hello,
I have a question regarding expected performance.

https://github.com/methodmissing/rbczmq reports to be able to reach ~200k messages per second.
While `cztop` seems to reach 37k messages per second.

Do you have any idea of the reason?

**Comment by paddor** [comment]
Hi! Good question.

Possible reasons:
* the reported speeds in rbczmq were done by sending bare strings (you can choose between `string`, `frame` and `message` through). The perf scripts in CZTop always send messages, which means more memory allocations in CZMQ (C) as well as CZTop (Ruby).
* as far as I can tell, rbczmq uses CZMQ 2.0.1, which has far less features and thus could be faster
* it's not obvious what Ruby implementation was used for those reports. It could be something other than MRI.

I've briefly profiled the library using ruby-prof, which tells me that the most time is spent in things like `<Module::CZMQ::FFI>#zmsg_send` and the like, meaning in CZMQ itself. So CZTop **should not** be the bottleneck, as far as I can tell.

I just changed the input_thru.rb script a bit to send and receive strings over the two PAIR sockets. I do that by directly using the FFI APIs, because CZTop currently doesn't have API to send and receive bare strings explicitly (it always uses the `zmsg_*()` APIs of CZMQ). If I run it with `./inproc_thru.rb 100 100_000` (100,000 100B messages), the throughput numbers look quite different even on my Late 2013 MacBook:

With MRI Ruby 2.4.2:
```
message size: 100 [B]
message count: 100000
elapsed time: 1.061 [s]
mean throughput: 94293 [msg/s]
mean throughput: 75.435 [Mb/s]
```

With JRuby 9.0.4.0:
```
message size: 100 [B]
message count: 100000
elapsed time: 0.244 [s]
mean throughput: 410315 [msg/s]
mean throughput: 328.252 [Mb/s]
```

See this [Gist](https://gist.github.com/paddor/bbbcc4d187be5e50470b49692e9b21ea) for the changed script.

So it really depends on what exactly you actually benchmark and which Ruby implementation you're using.

**Comment by prdn** [comment]
Thanks for your reply. That's sounds really promising then :-)
