### ISSUE TITLE
Support ZMQ 4.1 (or older)

### ISSUE THREAD

**Issue by rfestag** [paddor/cztop#8]
It would be nice if, even though Cztop is new, it supported the latest stable version of ZMQ (or further back for whatever is available by default in common distro repositories). From a comment @paddor posted (https://github.com/celluloid/celluloid-zmq/issues/56#issuecomment-209448148), this was becoming difficult, and 4.2 was nearly ready to release; that said, I haven't seen much movement on that front (granted, I'm not sure where to look, but a google search didn't bring up much). I was planning to just wait for 4.2 to come out (since I run Manjaro, I would suspect a 4.2 package update wouldn't be far behind). Unfortunately it hasn't come out yet, and I'm itching to play with this again. I try to avoid manually compiling/installing libraries, especially those that are depended on by system components (Cinnamon apparently uses it on my desktop). That's what I have a package manager for anyways =).

I was wondering what the main technical hurdle was for supporting older versions of ZMQ. Would it be feasible to create a few separate branches off cztop to support a handful of common ZMQ versions? I'd be happy to work on making whatever changes are necessary to support at least 4.1, but would be interested in understanding what it would take to ensure other builds could be supported as well (so I don't end up doing a complete one-off if possible).

**Comment by paddor** [comment]
I dropped support for ZMQ 4.1 in April. I can't remember from the top of my head why. Maybe you can find the exact reason in one of the commit messages. I'm pretty sure it was because of the combination of ZMQ 4.1/master, CZMQ master, the FFI code in czmq-ffi-gen (which depends on recent, but marked-as-stable (not draft) functions of CZMQ), ... I wrote the generator code in zproject for Ruby bindings to produce code that really depends on the availability of stable functions. Only draft functions are handled gracefully. Functions like `zlist_head` are new (unreleased?) but marked stable. Ther even has been an API change of the existing functions used to encode/decode stuff (like Z85). 

Oh and CZTop::Poller depends on zmq_poller_\* functions (to be able to work with thread-safe sockets), which are new (not in 4.1). 

My suggestion is to build ZMQ and CZMQ from master. If Munjaro is a derivate of Arch, I assume it's source based anyway. 

For the time being, you could use an older version of CZTop? Like the one before I dropped support for 4.1 in April? Apart from the Poller, it should be pretty much the same.

**Comment by rfestag** [comment]
Manjaro isn't source based (although you can install packages from AUR instead of pacman, but there aren't more recent AUR packages for zmq from git), and I suspect I would run into conflicts anyways because of the package dependency.

I looked through the commit history, and didn't see anything specific to 4.1's remove except documentation/CI changes.

I definitely understand it would be faster to just install ZMQ/CZMQ from source, but I'd be interested in figuring out a way to make CZTop work with packaged versions if feasible, if only to reduce the barrier to entry for others. 

If I wanted to delve deeper into this, would a better starting point be czmq-ffi-gen? I played with that a while back, but haven't touched it in months. I assume I would need to generate a czmq-ffi-gen gem from the 4.1 stable sources, and use that to start identifying where there are breaks?

**Comment by paddor** [comment]
I had the same goals as you. :)

I'm assuming you want to use released versions of both ZMQ and CZMQ. The ZMQ guys told me CZMQ is already VERY different from the released version, as I've mentioned [here](https://github.com/paddor/cztop/issues/4#issuecomment-203433507) once. If you wanna work on this, I guess you could install releases of ZMQ and CZMQ, and the `czmq-ffi-gen` gem, and then try to load it in an irb shell with `require 'czmq-ffi-gen'`. In case there are functions missing, it'll tell you. To even out discrepances, you could fix them within `czmq-ffi-gen`. This all sounds feasible to me, as long as you're working locally only. But releasing a version of czmq-ffi-gen and/or CZTop which support the current releases of ZMQ and CZMQ sounds infeasible to me, except under a different name, like appending `-legacy`? I don't know. 

Why not use the CZTop gem version 0.2.1? It supports ZMQ 4.0, 4.1 and CZMQ 3.0.2. (See [here](https://github.com/paddor/cztop/blob/master/CHANGES.md#030-13042016)).

**Comment by paddor** [comment]
Reviving this repo. Reopen if needed.
